command_timeout = 10000

add_newline = false

format = '''⚡'''

right_format = '''$all'''

[directory]
truncation_length = 1
format = '[$path]($style)'
read_only_style = '#E69875'
style = 'bold #7FBBB3'

[character]
disabled = true

[aws]
format = '[\[](bold blue)[$symbol($profile)(\($region\))(\[$duration[\]](bold blue))]($style)\]'
symbol = "  "

[buf]
symbol = " "

[bun]
format = '[\[](bold blue)[$symbol($version)]($style)[\]](bold blue)'

[c]
format = '[$symbol]($style)'
symbol = " "

[cmake]
format = '[\[](bold blue)[$symbol($version)]($style)[\]](bold blue)'

[cmd_duration]
format = '[\[](bold blue)[$duration]($style)[\]](bold blue)'
disabled = true

[cobol]
format = '[\[](bold blue)[$symbol($version)]($style)[\]](bold blue)'

[conda]
format = '[\[](bold blue)[$symbol$environment]($style)[\]](bold blue)'
symbol = " "

[crystal]
format = '[\[](bold blue)[$symbol($version)]($style)[\]](bold blue)'

[daml]
format = '[\[](bold blue)[$symbol($version)]($style)[\]](bold blue)'

[dart]
format = '[\[](bold blue)[$symbol($version)]($style)[\]](bold blue)'
symbol = " "

[deno]
format = '[\[](bold blue)[$symbol($version)]($style)[\]](bold blue)'

[docker_context]
format = '[\[](bold blue)[$symbol$context]($style)[\]](bold blue)'
symbol = " "

[dotnet]
format = '[\[](bold blue)[$symbol($version)(🎯 $tfm)]($style)[\]](bold blue)'

[elixir]
format = '[\[](bold blue)[$symbol($version \(OTP $otp_version\))]($style)[\]](bold blue)'
symbol = " "

[elm]
format = '[\[](bold blue)[$symbol($version)]($style)[\]](bold blue)'
symbol = " "

[erlang]
format = '[\[](bold blue)[$symbol($version)]($style)[\]](bold blue)'

[gcloud]
format = '[\[](bold blue)[$symbol$account(@$domain)(\($region\))]($style)[\]](bold blue)'

[git_branch]
format = " [$symbol$branch]($style)"
style = "bold yellow"

[git_commit]
commit_hash_length = 8
style = "bold white"

[git_state]
format = ' [\($state( $progress_current of $progress_total)\)]($style)'

[golang]
format = '[$symbol]($style)'
symbol = " "

[guix_shell]
format = '[\[](bold blue)[$symbol]($style)[\]](bold blue)'
symbol = " "

[haskell]
format = '[\[](bold blue)[$symbol($version)]($style)[\]](bold blue)'
symbol = " "

[haxe]
format = '[\[](bold blue)[$symbol($version)]($style)[\]](bold blue)'
symbol = "⌘ "

[helm]
format = '[\[](bold blue)[$symbol($version)]($style)[\]](bold blue)'

[hg_branch]
format = '[\[](bold blue)[$symbol$branch]($style)[\]](bold blue)'
symbol = " "

[java]
format = '[\[](bold blue)[$symbol($version)]($style)[\]](bold blue)'
symbol = " "

[julia]
format = '[\[](bold blue)[$symbol($version)]($style)[\]](bold blue)'
symbol = " "

[kotlin]
format = '[\[](bold blue)[$symbol($version)]($style)[\]](bold blue)'

[kubernetes]
format = '[\[](bold blue)[$symbol$context( \($namespace\))]($style)[\]](bold blue)'

[lua]
format = '[$symbol]($style)'
# format = ''
symbol = "  "

[memory_usage]
format = "$symbol[${ram}( | ${swap})]($style) "
threshold = 70
style = "bold dimmed white"
disabled = false

[meson]
format = '[\[](bold blue)[$symbol$project]($style)[\]](bold blue)'
symbol = "󰔷 "

[nim]
format = '[\[](bold blue)[$symbol($version)]($style)[\]](bold blue)'
symbol = "󰆥 "

[nix_shell]
format = '[\[](bold blue)[$symbol$state( \($name\))]($style)[\]](bold blue)'
symbol = " "

[nodejs]
format = '[$symbol]($style)'
symbol = "  "

[ocaml]
format = '[\[](bold blue)[$symbol($version)(\($switch_indicator$switch_name\))]($style)[\]](bold blue)'

[opa]
format = '[\[](bold blue)[$symbol($version)]($style)[\]](bold blue)'

[openstack]
format = '[\[](bold blue)[$symbol$cloud(\($project\))]($style)[\]](bold blue)'

[os]
format = '[\[](bold blue)[$symbol]($style)[\]](bold blue)'

[package]
format = '[$symbol]($style)'
symbol = "󰏗 "

[perl]
format = '[\[](bold blue)[$symbol($version)]($style)[\]](bold blue)'

[php]
format = '[\[](bold blue)[$symbol($version)]($style)[\]](bold blue)'

[pulumi]
format = '[\[](bold blue)[$symbol$stack]($style)[\]](bold blue)'

[purescript]
format = '[\[](bold blue)[$symbol($version)]($style)[\]](bold blue)'

[python]
format=''
# format = '[\[](bold blue)[${symbol}${pyenv_prefix}(${version})(\($virtualenv\))]($style)[\]](bold blue)'
symbol = " "

[raku]
format = '[\[](bold blue)[$symbol($version-$vm_version)]($style)[\]](bold blue)'

[red]
format = '[\[](bold blue)[$symbol($version)]($style)[\]](bold blue)'

[rlang]
symbol = "󰟔 "

[ruby]
format = '[\[](bold blue)[$symbol($version)]($style)[\]](bold blue)'
symbol = " "

[rust]
format = '[\[](bold blue)[$symbol($version)]($style)[\]](bold blue)'
symbol = "󱘗 "

[scala]
format = '[\[](bold blue)[$symbol($version)]($style)[\]](bold blue)'
symbol = " "

[spack]
format = '[\[](bold blue)[$symbol$environment]($style)[\]](bold blue)'
symbol = "🅢 "

[sudo]
format = '[\[](bold blue)[as $symbol][\]](bold blue)'

[swift]
format = '[\[](bold blue)[$symbol($version)]($style)[\]](bold blue)'

[terraform]
format = '[\[](bold blue)[$symbol$workspace]($style)[\]](bold blue)'

[time]
format = '[\[](bold blue)[$time]($style)[\]](bold blue)'

[username]
format = '[\[](bold blue)[$user]($style)[\]](bold blue)'

[vagrant]
format = '[\[](bold blue)[$symbol($version)]($style)[\]](bold blue)'

[vlang]
format = '[\[](bold blue)[$symbol($version)]($style)[\]](bold blue)'

[zig]
format = '[\[](bold blue)[$symbol($version)]($style)[\]](bold blue)'
