command_timeout = 10000

add_newline = false

# format = '''⚡'''
format = "🦊$hostname "
# format = "⚯ ͛$hostname "
# format = "⚡$hostname"

right_format = '''$all'''

[line_break]
disabled = true

[hostname]
ssh_only = true
format = '@[$hostname](bold yellow) '
trim_at = "."
disabled = false

[directory]
truncation_length = 1
format = '[$path]($style)'
truncation_symbol = " "
read_only_style = '#E69875'
style = 'bold #7FBBB3'

[character]
disabled = true

[cmd_duration]
min_time = 10_000
format = " took [$duration]($style)"

[aws]
format = '[\[](bold blue)[$symbol($profile)(\($region\))(\[$duration[\]](bold blue))]($style)\]'
symbol = "  "

[buf]
symbol = " "

[bun]
format = '[\[](bold blue)[$symbol($version)]($style)[\]](bold blue)'

[c]
format = '[$symbol]($style)'
symbol = "  "

[cmake]
format = '[\[](bold blue)[$symbol($version)]($style)[\]](bold blue)'

[cobol]
format = '[\[](bold blue)[$symbol($version)]($style)[\]](bold blue)'

[conda]
format = '[\[](bold blue)[$symbol$environment]($style)[\]](bold blue)'
symbol = " "

[crystal]
format = '[\[](bold blue)[$symbol($version)]($style)[\]](bold blue)'

[daml]
format = '[\[](bold blue)[$symbol($version)]($style)[\]](bold blue)'

[dart]
format = '[\[](bold blue)[$symbol($version)]($style)[\]](bold blue)'
symbol = " "

[deno]
format = '[\[](bold blue)[$symbol($version)]($style)[\]](bold blue)'

[docker_context]
format = '[\[](bold blue)[$symbol$context]($style)[\]](bold blue)'
symbol = " "

[dotnet]
format = '[\[](bold blue)[$symbol($version)(🎯 $tfm)]($style)[\]](bold blue)'

[elixir]
format = '[\[](bold blue)[$symbol($version \(OTP $otp_version\))]($style)[\]](bold blue)'
symbol = " "

[elm]
format = '[\[](bold blue)[$symbol($version)]($style)[\]](bold blue)'
symbol = " "

[erlang]
format = '[\[](bold blue)[$symbol($version)]($style)[\]](bold blue)'

[gcloud]
format = '[\[](bold blue)[$symbol$account(@$domain)(\($region\))]($style)[\]](bold blue)'

[git_branch]
format = " [$symbol$branch]($style) "
symbol = '🌱 '
# truncation_length = 4
truncation_symbol = ''
# ignore_branches = ['master', 'main']

# ~/.config/starship.toml

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '
cherry_pick = '[🍒 PICKING](bold red)'

[git_commit]
commit_hash_length = 4
tag_symbol = '🔖 '
style = "bold white"

[git_metrics]
added_style = "bold green"
deleted_style = "bold red"
only_nonzero_diffs = true
format = '([+$added]($added_style) )([-$deleted]($deleted_style) )'
disabled = true

[git_status]
conflicted = "⚔️ "
ahead = "⇡"
behind = "[⇣${count}](bold dimmed blue)"
diverged = "⇕${ahead_count}⇣${behind_count}"
untracked = "[?${count}](bold blue)"
modified ="[!${count}](bold yellow)"
staged = "[+${count}](bold yellow)"
renamed = "» ×${count}"
deleted = "[×${count}](bold red)"
format = "$all_status$ahead_behind"

[golang]
format = '[$symbol]($style)'
symbol = " "

[guix_shell]
format = '[\[](bold blue)[$symbol]($style)[\]](bold blue)'
symbol = " "

[haskell]
format = '[$symbol]($style)'
symbol = "  "

[haxe]
format = '[\[](bold blue)[$symbol($version)]($style)[\]](bold blue)'
symbol = "⌘ "

[helm]
format = '[\[](bold blue)[$symbol($version)]($style)[\]](bold blue)'

[hg_branch]
format = '[\[](bold blue)[$symbol$branch]($style)[\]](bold blue)'
symbol = " "

[java]
format = '[\[](bold blue)[$symbol($version)]($style)[\]](bold blue)'
symbol = " "

[julia]
format = '[\[](bold blue)[$symbol($version)]($style)[\]](bold blue)'
symbol = " "

[kotlin]
format = '[\[](bold blue)[$symbol($version)]($style)[\]](bold blue)'

[kubernetes]
format = '[\[](bold blue)[$symbol$context( \($namespace\))]($style)[\]](bold blue)'

[lua]
format = '[$symbol]($style)'
# format = ''
symbol = "  "

[memory_usage]
format = "$symbol[${ram}( | ${swap})]($style) "
threshold = 70
style = "bold dimmed white"
disabled = false

[meson]
format = '[\[](bold blue)[$symbol$project]($style)[\]](bold blue)'
symbol = "󰔷 "

[nim]
format = '[\[](bold blue)[$symbol($version)]($style)[\]](bold blue)'
symbol = "󰆥 "

[nix_shell]
format = '[\[](bold blue)[$symbol$state( \($name\))]($style)[\]](bold blue)'
symbol = " "

[nodejs]
format = '[$symbol]($style)'
symbol = "  "

[ocaml]
format = '[\[](bold blue)[$symbol($version)(\($switch_indicator$switch_name\))]($style)[\]](bold blue)'

[opa]
format = '[\[](bold blue)[$symbol($version)]($style)[\]](bold blue)'

[openstack]
format = '[\[](bold blue)[$symbol$cloud(\($project\))]($style)[\]](bold blue)'

[os]
format = '[\[](bold blue)[$symbol]($style)[\]](bold blue)'

[package]
format = '[$symbol]($style)'
symbol = "󰏗 "

[perl]
format = '[\[](bold blue)[$symbol($version)]($style)[\]](bold blue)'

[php]
format = '[\[](bold blue)[$symbol($version)]($style)[\]](bold blue)'

[pulumi]
format = '[\[](bold blue)[$symbol$stack]($style)[\]](bold blue)'

[purescript]
format = '[\[](bold blue)[$symbol($version)]($style)[\]](bold blue)'

[python]
format=''
# format = '[\[](bold blue)[${symbol}${pyenv_prefix}(${version})(\($virtualenv\))]($style)[\]](bold blue)'
symbol = " "

[raku]
format = '[\[](bold blue)[$symbol($version-$vm_version)]($style)[\]](bold blue)'

[red]
format = '[\[](bold blue)[$symbol($version)]($style)[\]](bold blue)'

[rlang]
symbol = "󰟔 "

[ruby]
format = '[\[](bold blue)[$symbol($version)]($style)[\]](bold blue)'
symbol = " "

[rust]
format = '[\[](bold blue)[$symbol($version)]($style)[\]](bold blue)'
symbol = "󱘗 "

[scala]
format = '[\[](bold blue)[$symbol($version)]($style)[\]](bold blue)'
symbol = " "

[spack]
format = '[\[](bold blue)[$symbol$environment]($style)[\]](bold blue)'
symbol = "🅢 "

[sudo]
format = '[\[](bold blue)[as $symbol][\]](bold blue)'

[swift]
format = '[\[](bold blue)[$symbol($version)]($style)[\]](bold blue)'

[terraform]
format = '[\[](bold blue)[$symbol$workspace]($style)[\]](bold blue)'

[time]
format = '[\[](bold blue)[$time]($style)[\]](bold blue)'

[username]
format = '[\[](bold blue)[$user]($style)[\]](bold blue)'

[vagrant]
format = '[\[](bold blue)[$symbol($version)]($style)[\]](bold blue)'

[vlang]
format = '[\[](bold blue)[$symbol($version)]($style)[\]](bold blue)'

[zig]
format = '[\[](bold blue)[$symbol($version)]($style)[\]](bold blue)'
