# $HOME/.config/alacritty/alacritty.toml
# by garfield 10-01-2024

[window]
opacity = 1.00
decorations = "None" # "None", "Full", "Transparent"
decorations_theme_variant = "Dark" # "Dark" or "Light"

[env]
# term = "xterm-256color"

[font]
normal.family = "JetBrainsMono Nerd Font"
bold.family = "JetBrainsMono Nerd Font"
#+Property: Header-args :tangle init.el
italic.family = "JetBrainsMono Nerd Font"
bold_italic.family = "JetBrainsMono Nerd Font"
size = 24.0

# [shell]
# program = "/usr/bin/fish"

# live_config_reload = true

[colors.primary]
background = '#272E33'
foreground = '#D5C9AB'

[colors.normal]
black   = '#7c8377'
red     = '#ed8082'
green   = '#a7c080'
yellow  = '#e69875'
blue    = '#6272a4'
magenta = '#d196b3'
cyan    = '#7fbbb3'
white   = '#D5C9AB'

[colors.bright]
black   = '#7c8377'
red     = '#ed8082'
green   = '#a7c080'
yellow  = '#e69875'
blue    = '#6272a4'
magenta = '#d196b3'
cyan    = '#7fbbb3'
white   = '#D5C9AB'

[colors.cursor]
text = "#1E1E2E"
cursor = "#F5E0DC"

[colors.vi_mode_cursor]
text = "#1E1E2E"
cursor = "#B4BEFE"

[colors.search.matches]
foreground = "#1E1E2E"
background = "#A6ADC8"

[colors.search.focused_match]
foreground = "#1E1E2E"
background = "#A6E3A1"

[colors.footer_bar]
foreground = "#1E1E2E"
background = "#A6ADC8"

[colors.hints.start]
foreground = "#1E1E2E"
background = "#F9E2AF"

[colors.hints.end]
foreground = "#1E1E2E"
background = "#A6ADC8"

[colors.selection]
text = "#1E1E2E"
background = "#F5E0DC"

[colors.dim]
black = "#45475A"
red = "#F38BA8"
green = "#A6E3A1"
yellow = "#F9E2AF"
blue = "#89B4FA"
magenta = "#F5C2E7"
cyan = "#94E2D5"
white = "#BAC2DE"

[[colors.indexed_colors]]
index = 16
color = "#FAB387"

[[colors.indexed_colors]]
index = 17
color = "#F5E0DC"

