[plugins]
"rocks.nvim" = "2.28.0"
tree-sitter-toml = "scm"
tree-sitter-lua = "scm"
"rocks-config.nvim" = "1.6.0"
"rocks-git.nvim" = "1.5.1"
"rocks-dev.nvim" = "1.2.1"
luarocks-build-treesitter-parser = "4.0.0"
"feline.nvim" = "1.6.0"
"staline.nvim" = "scm"
"better-escape.nvim" = "scm"
"focus.nvim" = "1.0.2"
nvim-surround = "2.1.5"
"rainbow-delimiters.nvim" = "0.4.0"
nvim-autopairs = "scm"
nvim-lspconfig = "0.1.7"
"indent-blankline.nvim" = "3.6.1"
"telescope.nvim" = "scm"
cmp-nvim-lsp = "scm"
nvim-cmp = "0.0.1"
luasnip = "2.3.0"
"mason.nvim" = "1.10.0"
"mason-lspconfig.nvim" = "1.29.0"
"conform.nvim" = "5.7.0"
auto-session = "2.0.1"
cmp-buffer = "scm"
cmp-path = "scm"
cmp_luasnip = "scm"
"lspkind.nvim" = "scm"
nvim-dap = "0.7.0"
nvim-dap-python = "scm"
nvim-dap-ui = "4.0.0"
nvim-dap-go = "scm"
"nui.nvim" = "0.3.0"
"noice.nvim" = "3.0.2"
fzf-lua = "0.0.1294"
# "incline.nvim" = "0.0.1"
# "tabby.nvim" = "2.4.1"
# "neo-tree.nvim" = "3.26"

[plugins."oil.nvim" ]
version = "scm"

[plugins.nvim-treesitter]
git = "nvim-treesitter/nvim-treesitter"

[plugins.nvim-smartbufs]
git = "johann2357/nvim-smartbufs"

[plugins.nvim-colorizer]
git = "NvChad/nvim-colorizer.lua"

[plugins."gitsigns.nvim"]
git = "lewis6991/gitsigns.nvim"

[plugins.everforest-nvim]
git = "neanias/everforest-nvim"

[plugins."telescope-fzf-native.nvim"]
git = "nvim-telescope/telescope-fzf-native.nvim"

[plugins.undotree]
git = "mbbill/undotree"

# [plugins."nnn.nvim"]
# git = "luukvbaal/nnn.nvim"

# --------- TREESITTER PARSERS ---------
tree-sitter-lua = "scm"
tree-sitter-vim = "scm"
tree-sitter-vimdoc = "scm"
tree-sitter-query = "scm"

[config]
plugins_dir = "plugins/"
auto_setup = true
